### PR TITLE
add pandas series

### LINKED ISSUE #117: support series structure of pandas

### PR DESCRIPTION
**Pull request by acezen**
## What do these changes do?

support Series structure of pandas

## Related issue number

Fixes #117

### CODE REVIEW

**Comment by acezen** [comment]
cc/ @sighingnow  @andydiwenzhu  any comment?

**Comment by andydiwenzhu** [comment]
LGTM

**Review by sighingnow — APPROVED** [review]
LGTM.

**Comment by sighingnow** [comment]
There's conflict after #110 merged. Could you rebase this PR agaist current main branch?

**Review by andydiwenzhu — COMMENTED** [review]
LGTM

**Comment by acezen** [comment]
> There's conflict after #110 merged. Could you rebase this PR agaist current main branch?

done.

**Pull request merged**
